language: php
php:
    - 5.6
    - 7
    - 7.1
    - hhvm
dist: trusty
matrix:
    allow_failures:
        -
            php: hhvm
        -
            python: 3.4
cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - 'composer self-update'
    - 'composer --version'
    - 'composer install --no-interaction'
    - './vendor/bin/hidev --version'
    - './vendor/bin/hidev travis/before-install'
python:
    - 2.7
    - 3.4
sudo: false
install:
    - './vendor/bin/hidev travis/install'
script:
    - './vendor/bin/hidev travis/script'
after_script:
    - './vendor/bin/hidev travis/after-script'
