language: python
python:
    - 2.7
    - 3.4
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
matrix:
    allow_failures:
        -
            php: hhvm
        -
            php: 5.5
        -
            python: 3.4
cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - 'composer self-update'
    - 'composer --version'
    - 'composer install --no-interaction'
    - './vendor/bin/hidev --version'
    - './vendor/bin/hidev travis/before_install'
sudo: false
install:
    - './vendor/bin/hidev travis/install'
script:
    - './vendor/bin/hidev travis/script'
after_script:
    - './vendor/bin/hidev travis/after_script'
