default:
    before:
        - LICENSE
        - README.md
        - .gitignore
        - .travis.yml
        - .scrutinizer.yml
install:
    before:
        - LICENSE
check:
    before:
        - LICENSE
test:
    before:
        - install
        - pytest
build:
    before:
        - check
        - test

readme:
    badges:
        github.version:
        scrutinizer.coverage:
        scrutinizer.quality:

pytest:
    coverage: true

.travis.yml:
    language: php
    php:
        - 7
    python:
        - 2.7
        - 3.4
    matrix:
        allow_failures:
            - python: 3.4

.scrutinizer.yml:
    checks:
        python:
            code_rating: true
            duplicate_code: true
    tools:
        external_code_coverage:
            timeout: 600
            runs:    1
