package:
    type:           yii2-extension
    name:           hidev-python
    title:          HiDev config for Python projects
    headline:       HiDev Python
    keywords:       hidev, config, python
    namespace:      hidev\python
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.

        This plugin enables HiDev for Python projects.

        Provides:

        - standart: LICENSE, README.md, CHANGELOG.md
        - CI: Travis & Scrutinizer
        - to be done: PyPI, pylint, autopep8, ...

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-travis:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
