package:
    name:           hidev-config-python
    namespace:      hiqdev\hidev\config\python
    label:          HiDevConfigPython
    title:          Hidev config for Python projects
    type:           yii2-extension
    keywords:       hidev, config, python
    year:           2015
    description:    |
        Basics for Python projects:
        - standart: LICENSE, README.md, CHANGELOG.md

require:
    hiqdev/hidev-config:        "*@dev"
    hiqdev/hidev-config-php:    "*@dev"
